# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AD', 'Admin'), ('AV', 'Projector Troubleshooting'), ('KC', 'Knows Campus'), ('FA', 'First Aid Trained')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('UR', 'Urgent'), ('ME', 'Medium'), ('NU', 'Not urgent, but needs to happen'), ('NI', 'Would be nice')], max_length=2)),
                ('min_time', models.DateTimeField()),
                ('max_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('TD', 'Todo'), ('IP', 'In Progress'), ('CP', 'Completed'), ('VO', 'Voided')], max_length=2)),
                ('skills', models.ManyToManyField(to='securityApp.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('can_text', models.BooleanField()),
                ('currently_here', models.BooleanField(default=False)),
                ('comments', models.TextField()),
                ('shifts', models.ManyToManyField(to='securityApp.Shift')),
                ('skills', models.ManyToManyField(to='securityApp.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='volunteers',
            field=models.ManyToManyField(to='securityApp.Volunteer'),
        ),
    ]
