# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='shifts',
            field=models.ManyToManyField(blank=True, to='securityApp.Shift'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='securityApp.Skill'),
        ),
    ]
