# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0003_auto_20160227_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='skills',
        ),
        migrations.AddField(
            model_name='task',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AD', 'Admin'), ('AV', 'Projector Troubleshooting'), ('KC', 'Knows Campus'), ('FA', 'First Aid Trained')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TD', 'Todo'), ('IP', 'In Progress'), ('CP', 'Completed'), ('VO', 'Voided')], default='TD', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='securityApp.Volunteer'),
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skills',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AD', 'Admin'), ('AV', 'Projector Troubleshooting'), ('KC', 'Knows Campus'), ('FA', 'First Aid Trained')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
